
name: Java CI/CD with Gradle

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read
  actions: read
  
env:
  IMAGE_NAME: hana-docker-image:latest
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: application.properties
      run: |
        mkdir -p src/main/resources
        touch ./src/main/resources/application.properties
        echo "${{ secrets.APPLICATION }}" >> ./src/main/resources/application.properties

    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
      
    - name: build gradle
      run: ./gradlew build
        
    - name: Docker Login
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Docker Setup Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build and push Docker images
      uses: docker/build-push-action@v4
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}

    
        


    
        
 
